server:
  port: 8080

spring:
  config:
    activate:
      on-profile: test-db
  r2dbc:
    url: r2dbc:h2:mem:///demo?options=DB_CLOSE_DELAY=1;;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
    username: sa
    password: